service: rtglabs-go

image: alka7ex/rtglabs-go

servers:
  web:
    - 103.127.134.82 
proxy:
  ssl: true
  host: api.rtglabs.net  
  app_port: 8080 
  healthcheck:
    interval: 10 
    path: /health 

registry:
  username: alka7ex  
  password:
    - KAMAL_REGISTRY_PASSWORD 

builder:
  arch: amd64 

env:
  clear:
    PORT: 8080 
    APP_ENV: production  
    SMTP_HOST: "smtp-relay.brevo.com"
    SMTP_PORT: "587"
    SMTP_USERNAME: "8f3b8e001@smtp-brevo.com"
    SMTP_FROM_EMAIL: "connect@rtglabs.net"
    APP_BASE_URL: https://api3.rtglabs.net
    DB_DRIVER: "postgres"
  secret:
    - DATABASE_URL 
    - SMTP_PASSWORD 

ssh:
  user: alka7ex

