// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rtglabs-go/ent/bodyweight"
	"rtglabs-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BodyweightDelete is the builder for deleting a Bodyweight entity.
type BodyweightDelete struct {
	config
	hooks    []Hook
	mutation *BodyweightMutation
}

// Where appends a list predicates to the BodyweightDelete builder.
func (bd *BodyweightDelete) Where(ps ...predicate.Bodyweight) *BodyweightDelete {
	bd.mutation.Where(ps...)
	return bd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bd *BodyweightDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bd.sqlExec, bd.mutation, bd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bd *BodyweightDelete) ExecX(ctx context.Context) int {
	n, err := bd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bd *BodyweightDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bodyweight.Table, sqlgraph.NewFieldSpec(bodyweight.FieldID, field.TypeUUID))
	if ps := bd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bd.mutation.done = true
	return affected, err
}

// BodyweightDeleteOne is the builder for deleting a single Bodyweight entity.
type BodyweightDeleteOne struct {
	bd *BodyweightDelete
}

// Where appends a list predicates to the BodyweightDelete builder.
func (bdo *BodyweightDeleteOne) Where(ps ...predicate.Bodyweight) *BodyweightDeleteOne {
	bdo.bd.mutation.Where(ps...)
	return bdo
}

// Exec executes the deletion query.
func (bdo *BodyweightDeleteOne) Exec(ctx context.Context) error {
	n, err := bdo.bd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bodyweight.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bdo *BodyweightDeleteOne) ExecX(ctx context.Context) {
	if err := bdo.Exec(ctx); err != nil {
		panic(err)
	}
}
