// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rtglabs-go/ent/exercise"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Exercise is the model entity for the Exercise schema.
type Exercise struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExerciseQuery when eager-loading is set.
	Edges        ExerciseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExerciseEdges holds the relations/edges for other nodes in the graph.
type ExerciseEdges struct {
	// ExerciseInstances holds the value of the exercise_instances edge.
	ExerciseInstances []*ExerciseInstance `json:"exercise_instances,omitempty"`
	// WorkoutExercises holds the value of the workout_exercises edge.
	WorkoutExercises []*WorkoutExercise `json:"workout_exercises,omitempty"`
	// ExerciseSets holds the value of the exercise_sets edge.
	ExerciseSets []*ExerciseSet `json:"exercise_sets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ExerciseInstancesOrErr returns the ExerciseInstances value or an error if the edge
// was not loaded in eager-loading.
func (e ExerciseEdges) ExerciseInstancesOrErr() ([]*ExerciseInstance, error) {
	if e.loadedTypes[0] {
		return e.ExerciseInstances, nil
	}
	return nil, &NotLoadedError{edge: "exercise_instances"}
}

// WorkoutExercisesOrErr returns the WorkoutExercises value or an error if the edge
// was not loaded in eager-loading.
func (e ExerciseEdges) WorkoutExercisesOrErr() ([]*WorkoutExercise, error) {
	if e.loadedTypes[1] {
		return e.WorkoutExercises, nil
	}
	return nil, &NotLoadedError{edge: "workout_exercises"}
}

// ExerciseSetsOrErr returns the ExerciseSets value or an error if the edge
// was not loaded in eager-loading.
func (e ExerciseEdges) ExerciseSetsOrErr() ([]*ExerciseSet, error) {
	if e.loadedTypes[2] {
		return e.ExerciseSets, nil
	}
	return nil, &NotLoadedError{edge: "exercise_sets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Exercise) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exercise.FieldName:
			values[i] = new(sql.NullString)
		case exercise.FieldCreatedAt, exercise.FieldUpdatedAt, exercise.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case exercise.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Exercise fields.
func (e *Exercise) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exercise.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				e.ID = *value
			}
		case exercise.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case exercise.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		case exercise.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				e.DeletedAt = new(time.Time)
				*e.DeletedAt = value.Time
			}
		case exercise.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				e.Name = value.String
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Exercise.
// This includes values selected through modifiers, order, etc.
func (e *Exercise) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// QueryExerciseInstances queries the "exercise_instances" edge of the Exercise entity.
func (e *Exercise) QueryExerciseInstances() *ExerciseInstanceQuery {
	return NewExerciseClient(e.config).QueryExerciseInstances(e)
}

// QueryWorkoutExercises queries the "workout_exercises" edge of the Exercise entity.
func (e *Exercise) QueryWorkoutExercises() *WorkoutExerciseQuery {
	return NewExerciseClient(e.config).QueryWorkoutExercises(e)
}

// QueryExerciseSets queries the "exercise_sets" edge of the Exercise entity.
func (e *Exercise) QueryExerciseSets() *ExerciseSetQuery {
	return NewExerciseClient(e.config).QueryExerciseSets(e)
}

// Update returns a builder for updating this Exercise.
// Note that you need to call Exercise.Unwrap() before calling this method if this Exercise
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Exercise) Update() *ExerciseUpdateOne {
	return NewExerciseClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Exercise entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Exercise) Unwrap() *Exercise {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Exercise is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Exercise) String() string {
	var builder strings.Builder
	builder.WriteString("Exercise(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := e.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(e.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Exercises is a parsable slice of Exercise.
type Exercises []*Exercise
