// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rtglabs-go/ent/exerciseinstance"
	"rtglabs-go/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExerciseInstanceQuery is the builder for querying ExerciseInstance entities.
type ExerciseInstanceQuery struct {
	config
	ctx        *QueryContext
	order      []exerciseinstance.OrderOption
	inters     []Interceptor
	predicates []predicate.ExerciseInstance
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExerciseInstanceQuery builder.
func (eiq *ExerciseInstanceQuery) Where(ps ...predicate.ExerciseInstance) *ExerciseInstanceQuery {
	eiq.predicates = append(eiq.predicates, ps...)
	return eiq
}

// Limit the number of records to be returned by this query.
func (eiq *ExerciseInstanceQuery) Limit(limit int) *ExerciseInstanceQuery {
	eiq.ctx.Limit = &limit
	return eiq
}

// Offset to start from.
func (eiq *ExerciseInstanceQuery) Offset(offset int) *ExerciseInstanceQuery {
	eiq.ctx.Offset = &offset
	return eiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eiq *ExerciseInstanceQuery) Unique(unique bool) *ExerciseInstanceQuery {
	eiq.ctx.Unique = &unique
	return eiq
}

// Order specifies how the records should be ordered.
func (eiq *ExerciseInstanceQuery) Order(o ...exerciseinstance.OrderOption) *ExerciseInstanceQuery {
	eiq.order = append(eiq.order, o...)
	return eiq
}

// First returns the first ExerciseInstance entity from the query.
// Returns a *NotFoundError when no ExerciseInstance was found.
func (eiq *ExerciseInstanceQuery) First(ctx context.Context) (*ExerciseInstance, error) {
	nodes, err := eiq.Limit(1).All(setContextOp(ctx, eiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exerciseinstance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) FirstX(ctx context.Context) *ExerciseInstance {
	node, err := eiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExerciseInstance ID from the query.
// Returns a *NotFoundError when no ExerciseInstance ID was found.
func (eiq *ExerciseInstanceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eiq.Limit(1).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exerciseinstance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := eiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExerciseInstance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExerciseInstance entity is found.
// Returns a *NotFoundError when no ExerciseInstance entities are found.
func (eiq *ExerciseInstanceQuery) Only(ctx context.Context) (*ExerciseInstance, error) {
	nodes, err := eiq.Limit(2).All(setContextOp(ctx, eiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exerciseinstance.Label}
	default:
		return nil, &NotSingularError{exerciseinstance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) OnlyX(ctx context.Context) *ExerciseInstance {
	node, err := eiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExerciseInstance ID in the query.
// Returns a *NotSingularError when more than one ExerciseInstance ID is found.
// Returns a *NotFoundError when no entities are found.
func (eiq *ExerciseInstanceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eiq.Limit(2).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exerciseinstance.Label}
	default:
		err = &NotSingularError{exerciseinstance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := eiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExerciseInstances.
func (eiq *ExerciseInstanceQuery) All(ctx context.Context) ([]*ExerciseInstance, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryAll)
	if err := eiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExerciseInstance, *ExerciseInstanceQuery]()
	return withInterceptors[[]*ExerciseInstance](ctx, eiq, qr, eiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) AllX(ctx context.Context) []*ExerciseInstance {
	nodes, err := eiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExerciseInstance IDs.
func (eiq *ExerciseInstanceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if eiq.ctx.Unique == nil && eiq.path != nil {
		eiq.Unique(true)
	}
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryIDs)
	if err = eiq.Select(exerciseinstance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := eiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eiq *ExerciseInstanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryCount)
	if err := eiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eiq, querierCount[*ExerciseInstanceQuery](), eiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) CountX(ctx context.Context) int {
	count, err := eiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eiq *ExerciseInstanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryExist)
	switch _, err := eiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eiq *ExerciseInstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := eiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExerciseInstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eiq *ExerciseInstanceQuery) Clone() *ExerciseInstanceQuery {
	if eiq == nil {
		return nil
	}
	return &ExerciseInstanceQuery{
		config:     eiq.config,
		ctx:        eiq.ctx.Clone(),
		order:      append([]exerciseinstance.OrderOption{}, eiq.order...),
		inters:     append([]Interceptor{}, eiq.inters...),
		predicates: append([]predicate.ExerciseInstance{}, eiq.predicates...),
		// clone intermediate query.
		sql:  eiq.sql.Clone(),
		path: eiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExerciseInstance.Query().
//		GroupBy(exerciseinstance.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eiq *ExerciseInstanceQuery) GroupBy(field string, fields ...string) *ExerciseInstanceGroupBy {
	eiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExerciseInstanceGroupBy{build: eiq}
	grbuild.flds = &eiq.ctx.Fields
	grbuild.label = exerciseinstance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.ExerciseInstance.Query().
//		Select(exerciseinstance.FieldCreateTime).
//		Scan(ctx, &v)
func (eiq *ExerciseInstanceQuery) Select(fields ...string) *ExerciseInstanceSelect {
	eiq.ctx.Fields = append(eiq.ctx.Fields, fields...)
	sbuild := &ExerciseInstanceSelect{ExerciseInstanceQuery: eiq}
	sbuild.label = exerciseinstance.Label
	sbuild.flds, sbuild.scan = &eiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExerciseInstanceSelect configured with the given aggregations.
func (eiq *ExerciseInstanceQuery) Aggregate(fns ...AggregateFunc) *ExerciseInstanceSelect {
	return eiq.Select().Aggregate(fns...)
}

func (eiq *ExerciseInstanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eiq); err != nil {
				return err
			}
		}
	}
	for _, f := range eiq.ctx.Fields {
		if !exerciseinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eiq.path != nil {
		prev, err := eiq.path(ctx)
		if err != nil {
			return err
		}
		eiq.sql = prev
	}
	return nil
}

func (eiq *ExerciseInstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExerciseInstance, error) {
	var (
		nodes = []*ExerciseInstance{}
		_spec = eiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExerciseInstance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExerciseInstance{config: eiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eiq *ExerciseInstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eiq.querySpec()
	_spec.Node.Columns = eiq.ctx.Fields
	if len(eiq.ctx.Fields) > 0 {
		_spec.Unique = eiq.ctx.Unique != nil && *eiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eiq.driver, _spec)
}

func (eiq *ExerciseInstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exerciseinstance.Table, exerciseinstance.Columns, sqlgraph.NewFieldSpec(exerciseinstance.FieldID, field.TypeUUID))
	_spec.From = eiq.sql
	if unique := eiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eiq.path != nil {
		_spec.Unique = true
	}
	if fields := eiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exerciseinstance.FieldID)
		for i := range fields {
			if fields[i] != exerciseinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eiq *ExerciseInstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eiq.driver.Dialect())
	t1 := builder.Table(exerciseinstance.Table)
	columns := eiq.ctx.Fields
	if len(columns) == 0 {
		columns = exerciseinstance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eiq.sql != nil {
		selector = eiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eiq.ctx.Unique != nil && *eiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eiq.predicates {
		p(selector)
	}
	for _, p := range eiq.order {
		p(selector)
	}
	if offset := eiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExerciseInstanceGroupBy is the group-by builder for ExerciseInstance entities.
type ExerciseInstanceGroupBy struct {
	selector
	build *ExerciseInstanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eigb *ExerciseInstanceGroupBy) Aggregate(fns ...AggregateFunc) *ExerciseInstanceGroupBy {
	eigb.fns = append(eigb.fns, fns...)
	return eigb
}

// Scan applies the selector query and scans the result into the given value.
func (eigb *ExerciseInstanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eigb.build.ctx, ent.OpQueryGroupBy)
	if err := eigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExerciseInstanceQuery, *ExerciseInstanceGroupBy](ctx, eigb.build, eigb, eigb.build.inters, v)
}

func (eigb *ExerciseInstanceGroupBy) sqlScan(ctx context.Context, root *ExerciseInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eigb.fns))
	for _, fn := range eigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eigb.flds)+len(eigb.fns))
		for _, f := range *eigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExerciseInstanceSelect is the builder for selecting fields of ExerciseInstance entities.
type ExerciseInstanceSelect struct {
	*ExerciseInstanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eis *ExerciseInstanceSelect) Aggregate(fns ...AggregateFunc) *ExerciseInstanceSelect {
	eis.fns = append(eis.fns, fns...)
	return eis
}

// Scan applies the selector query and scans the result into the given value.
func (eis *ExerciseInstanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eis.ctx, ent.OpQuerySelect)
	if err := eis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExerciseInstanceQuery, *ExerciseInstanceSelect](ctx, eis.ExerciseInstanceQuery, eis, eis.inters, v)
}

func (eis *ExerciseInstanceSelect) sqlScan(ctx context.Context, root *ExerciseInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eis.fns))
	for _, fn := range eis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
