// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rtglabs-go/ent/exerciseinstance"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ExerciseInstance is the model entity for the ExerciseInstance schema.
type ExerciseInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// WorkoutLogID holds the value of the "workout_log_id" field.
	WorkoutLogID *uuid.UUID `json:"workout_log_id,omitempty"`
	// ExerciseID holds the value of the "exercise_id" field.
	ExerciseID   uuid.UUID `json:"exercise_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExerciseInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exerciseinstance.FieldWorkoutLogID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case exerciseinstance.FieldCreateTime, exerciseinstance.FieldUpdateTime, exerciseinstance.FieldCreatedAt, exerciseinstance.FieldUpdatedAt, exerciseinstance.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case exerciseinstance.FieldID, exerciseinstance.FieldExerciseID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExerciseInstance fields.
func (ei *ExerciseInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exerciseinstance.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ei.ID = *value
			}
		case exerciseinstance.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ei.CreateTime = value.Time
			}
		case exerciseinstance.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ei.UpdateTime = value.Time
			}
		case exerciseinstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ei.CreatedAt = value.Time
			}
		case exerciseinstance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ei.UpdatedAt = value.Time
			}
		case exerciseinstance.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ei.DeletedAt = new(time.Time)
				*ei.DeletedAt = value.Time
			}
		case exerciseinstance.FieldWorkoutLogID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field workout_log_id", values[i])
			} else if value.Valid {
				ei.WorkoutLogID = new(uuid.UUID)
				*ei.WorkoutLogID = *value.S.(*uuid.UUID)
			}
		case exerciseinstance.FieldExerciseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field exercise_id", values[i])
			} else if value != nil {
				ei.ExerciseID = *value
			}
		default:
			ei.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExerciseInstance.
// This includes values selected through modifiers, order, etc.
func (ei *ExerciseInstance) Value(name string) (ent.Value, error) {
	return ei.selectValues.Get(name)
}

// Update returns a builder for updating this ExerciseInstance.
// Note that you need to call ExerciseInstance.Unwrap() before calling this method if this ExerciseInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (ei *ExerciseInstance) Update() *ExerciseInstanceUpdateOne {
	return NewExerciseInstanceClient(ei.config).UpdateOne(ei)
}

// Unwrap unwraps the ExerciseInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ei *ExerciseInstance) Unwrap() *ExerciseInstance {
	_tx, ok := ei.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExerciseInstance is not a transactional entity")
	}
	ei.config.driver = _tx.drv
	return ei
}

// String implements the fmt.Stringer.
func (ei *ExerciseInstance) String() string {
	var builder strings.Builder
	builder.WriteString("ExerciseInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ei.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ei.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ei.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ei.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ei.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ei.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ei.WorkoutLogID; v != nil {
		builder.WriteString("workout_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("exercise_id=")
	builder.WriteString(fmt.Sprintf("%v", ei.ExerciseID))
	builder.WriteByte(')')
	return builder.String()
}

// ExerciseInstances is a parsable slice of ExerciseInstance.
type ExerciseInstances []*ExerciseInstance
