// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"rtglabs-go/ent/exercise"
	"rtglabs-go/ent/exerciseinstance"
	"rtglabs-go/ent/predicate"
	"rtglabs-go/ent/workoutexercise"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExerciseQuery is the builder for querying Exercise entities.
type ExerciseQuery struct {
	config
	ctx                   *QueryContext
	order                 []exercise.OrderOption
	inters                []Interceptor
	predicates            []predicate.Exercise
	withExerciseInstances *ExerciseInstanceQuery
	withWorkoutExercises  *WorkoutExerciseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExerciseQuery builder.
func (eq *ExerciseQuery) Where(ps ...predicate.Exercise) *ExerciseQuery {
	eq.predicates = append(eq.predicates, ps...)
	return eq
}

// Limit the number of records to be returned by this query.
func (eq *ExerciseQuery) Limit(limit int) *ExerciseQuery {
	eq.ctx.Limit = &limit
	return eq
}

// Offset to start from.
func (eq *ExerciseQuery) Offset(offset int) *ExerciseQuery {
	eq.ctx.Offset = &offset
	return eq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eq *ExerciseQuery) Unique(unique bool) *ExerciseQuery {
	eq.ctx.Unique = &unique
	return eq
}

// Order specifies how the records should be ordered.
func (eq *ExerciseQuery) Order(o ...exercise.OrderOption) *ExerciseQuery {
	eq.order = append(eq.order, o...)
	return eq
}

// QueryExerciseInstances chains the current query on the "exercise_instances" edge.
func (eq *ExerciseQuery) QueryExerciseInstances() *ExerciseInstanceQuery {
	query := (&ExerciseInstanceClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exercise.Table, exercise.FieldID, selector),
			sqlgraph.To(exerciseinstance.Table, exerciseinstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exercise.ExerciseInstancesTable, exercise.ExerciseInstancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkoutExercises chains the current query on the "workout_exercises" edge.
func (eq *ExerciseQuery) QueryWorkoutExercises() *WorkoutExerciseQuery {
	query := (&WorkoutExerciseClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exercise.Table, exercise.FieldID, selector),
			sqlgraph.To(workoutexercise.Table, workoutexercise.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exercise.WorkoutExercisesTable, exercise.WorkoutExercisesColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Exercise entity from the query.
// Returns a *NotFoundError when no Exercise was found.
func (eq *ExerciseQuery) First(ctx context.Context) (*Exercise, error) {
	nodes, err := eq.Limit(1).All(setContextOp(ctx, eq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exercise.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eq *ExerciseQuery) FirstX(ctx context.Context) *Exercise {
	node, err := eq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Exercise ID from the query.
// Returns a *NotFoundError when no Exercise ID was found.
func (eq *ExerciseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eq.Limit(1).IDs(setContextOp(ctx, eq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exercise.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eq *ExerciseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := eq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Exercise entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Exercise entity is found.
// Returns a *NotFoundError when no Exercise entities are found.
func (eq *ExerciseQuery) Only(ctx context.Context) (*Exercise, error) {
	nodes, err := eq.Limit(2).All(setContextOp(ctx, eq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exercise.Label}
	default:
		return nil, &NotSingularError{exercise.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eq *ExerciseQuery) OnlyX(ctx context.Context) *Exercise {
	node, err := eq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Exercise ID in the query.
// Returns a *NotSingularError when more than one Exercise ID is found.
// Returns a *NotFoundError when no entities are found.
func (eq *ExerciseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eq.Limit(2).IDs(setContextOp(ctx, eq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exercise.Label}
	default:
		err = &NotSingularError{exercise.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eq *ExerciseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := eq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Exercises.
func (eq *ExerciseQuery) All(ctx context.Context) ([]*Exercise, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryAll)
	if err := eq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Exercise, *ExerciseQuery]()
	return withInterceptors[[]*Exercise](ctx, eq, qr, eq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eq *ExerciseQuery) AllX(ctx context.Context) []*Exercise {
	nodes, err := eq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Exercise IDs.
func (eq *ExerciseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if eq.ctx.Unique == nil && eq.path != nil {
		eq.Unique(true)
	}
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryIDs)
	if err = eq.Select(exercise.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eq *ExerciseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := eq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eq *ExerciseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryCount)
	if err := eq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eq, querierCount[*ExerciseQuery](), eq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eq *ExerciseQuery) CountX(ctx context.Context) int {
	count, err := eq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eq *ExerciseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryExist)
	switch _, err := eq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eq *ExerciseQuery) ExistX(ctx context.Context) bool {
	exist, err := eq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExerciseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eq *ExerciseQuery) Clone() *ExerciseQuery {
	if eq == nil {
		return nil
	}
	return &ExerciseQuery{
		config:                eq.config,
		ctx:                   eq.ctx.Clone(),
		order:                 append([]exercise.OrderOption{}, eq.order...),
		inters:                append([]Interceptor{}, eq.inters...),
		predicates:            append([]predicate.Exercise{}, eq.predicates...),
		withExerciseInstances: eq.withExerciseInstances.Clone(),
		withWorkoutExercises:  eq.withWorkoutExercises.Clone(),
		// clone intermediate query.
		sql:  eq.sql.Clone(),
		path: eq.path,
	}
}

// WithExerciseInstances tells the query-builder to eager-load the nodes that are connected to
// the "exercise_instances" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ExerciseQuery) WithExerciseInstances(opts ...func(*ExerciseInstanceQuery)) *ExerciseQuery {
	query := (&ExerciseInstanceClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withExerciseInstances = query
	return eq
}

// WithWorkoutExercises tells the query-builder to eager-load the nodes that are connected to
// the "workout_exercises" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ExerciseQuery) WithWorkoutExercises(opts ...func(*WorkoutExerciseQuery)) *ExerciseQuery {
	query := (&WorkoutExerciseClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withWorkoutExercises = query
	return eq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Exercise.Query().
//		GroupBy(exercise.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eq *ExerciseQuery) GroupBy(field string, fields ...string) *ExerciseGroupBy {
	eq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExerciseGroupBy{build: eq}
	grbuild.flds = &eq.ctx.Fields
	grbuild.label = exercise.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Exercise.Query().
//		Select(exercise.FieldCreatedAt).
//		Scan(ctx, &v)
func (eq *ExerciseQuery) Select(fields ...string) *ExerciseSelect {
	eq.ctx.Fields = append(eq.ctx.Fields, fields...)
	sbuild := &ExerciseSelect{ExerciseQuery: eq}
	sbuild.label = exercise.Label
	sbuild.flds, sbuild.scan = &eq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExerciseSelect configured with the given aggregations.
func (eq *ExerciseQuery) Aggregate(fns ...AggregateFunc) *ExerciseSelect {
	return eq.Select().Aggregate(fns...)
}

func (eq *ExerciseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eq); err != nil {
				return err
			}
		}
	}
	for _, f := range eq.ctx.Fields {
		if !exercise.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eq.path != nil {
		prev, err := eq.path(ctx)
		if err != nil {
			return err
		}
		eq.sql = prev
	}
	return nil
}

func (eq *ExerciseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Exercise, error) {
	var (
		nodes       = []*Exercise{}
		_spec       = eq.querySpec()
		loadedTypes = [2]bool{
			eq.withExerciseInstances != nil,
			eq.withWorkoutExercises != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Exercise).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Exercise{config: eq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eq.withExerciseInstances; query != nil {
		if err := eq.loadExerciseInstances(ctx, query, nodes,
			func(n *Exercise) { n.Edges.ExerciseInstances = []*ExerciseInstance{} },
			func(n *Exercise, e *ExerciseInstance) {
				n.Edges.ExerciseInstances = append(n.Edges.ExerciseInstances, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := eq.withWorkoutExercises; query != nil {
		if err := eq.loadWorkoutExercises(ctx, query, nodes,
			func(n *Exercise) { n.Edges.WorkoutExercises = []*WorkoutExercise{} },
			func(n *Exercise, e *WorkoutExercise) { n.Edges.WorkoutExercises = append(n.Edges.WorkoutExercises, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eq *ExerciseQuery) loadExerciseInstances(ctx context.Context, query *ExerciseInstanceQuery, nodes []*Exercise, init func(*Exercise), assign func(*Exercise, *ExerciseInstance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Exercise)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ExerciseInstance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exercise.ExerciseInstancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.exercise_exercise_instances
		if fk == nil {
			return fmt.Errorf(`foreign-key "exercise_exercise_instances" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exercise_exercise_instances" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (eq *ExerciseQuery) loadWorkoutExercises(ctx context.Context, query *WorkoutExerciseQuery, nodes []*Exercise, init func(*Exercise), assign func(*Exercise, *WorkoutExercise)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Exercise)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WorkoutExercise(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exercise.WorkoutExercisesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.exercise_workout_exercises
		if fk == nil {
			return fmt.Errorf(`foreign-key "exercise_workout_exercises" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exercise_workout_exercises" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eq *ExerciseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eq.querySpec()
	_spec.Node.Columns = eq.ctx.Fields
	if len(eq.ctx.Fields) > 0 {
		_spec.Unique = eq.ctx.Unique != nil && *eq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eq.driver, _spec)
}

func (eq *ExerciseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exercise.Table, exercise.Columns, sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID))
	_spec.From = eq.sql
	if unique := eq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eq.path != nil {
		_spec.Unique = true
	}
	if fields := eq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exercise.FieldID)
		for i := range fields {
			if fields[i] != exercise.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eq *ExerciseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eq.driver.Dialect())
	t1 := builder.Table(exercise.Table)
	columns := eq.ctx.Fields
	if len(columns) == 0 {
		columns = exercise.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eq.sql != nil {
		selector = eq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eq.ctx.Unique != nil && *eq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eq.predicates {
		p(selector)
	}
	for _, p := range eq.order {
		p(selector)
	}
	if offset := eq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExerciseGroupBy is the group-by builder for Exercise entities.
type ExerciseGroupBy struct {
	selector
	build *ExerciseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (egb *ExerciseGroupBy) Aggregate(fns ...AggregateFunc) *ExerciseGroupBy {
	egb.fns = append(egb.fns, fns...)
	return egb
}

// Scan applies the selector query and scans the result into the given value.
func (egb *ExerciseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, egb.build.ctx, ent.OpQueryGroupBy)
	if err := egb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExerciseQuery, *ExerciseGroupBy](ctx, egb.build, egb, egb.build.inters, v)
}

func (egb *ExerciseGroupBy) sqlScan(ctx context.Context, root *ExerciseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(egb.fns))
	for _, fn := range egb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*egb.flds)+len(egb.fns))
		for _, f := range *egb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*egb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := egb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExerciseSelect is the builder for selecting fields of Exercise entities.
type ExerciseSelect struct {
	*ExerciseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (es *ExerciseSelect) Aggregate(fns ...AggregateFunc) *ExerciseSelect {
	es.fns = append(es.fns, fns...)
	return es
}

// Scan applies the selector query and scans the result into the given value.
func (es *ExerciseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, es.ctx, ent.OpQuerySelect)
	if err := es.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExerciseQuery, *ExerciseSelect](ctx, es.ExerciseQuery, es, es.inters, v)
}

func (es *ExerciseSelect) sqlScan(ctx context.Context, root *ExerciseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(es.fns))
	for _, fn := range es.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*es.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := es.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
