// Code generated by ent, DO NOT EDIT.

package ent

import (
	"rtglabs-go/ent/bodyweight"
	"rtglabs-go/ent/exercise"
	"rtglabs-go/ent/exerciseinstance"
	"rtglabs-go/ent/exerciseset"
	"rtglabs-go/ent/privatetoken"
	"rtglabs-go/ent/profile"
	"rtglabs-go/ent/schema"
	"rtglabs-go/ent/session"
	"rtglabs-go/ent/user"
	"rtglabs-go/ent/workout"
	"rtglabs-go/ent/workoutexercise"
	"rtglabs-go/ent/workoutlog"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bodyweightMixin := schema.Bodyweight{}.Mixin()
	bodyweightMixinFields0 := bodyweightMixin[0].Fields()
	_ = bodyweightMixinFields0
	bodyweightMixinFields1 := bodyweightMixin[1].Fields()
	_ = bodyweightMixinFields1
	bodyweightFields := schema.Bodyweight{}.Fields()
	_ = bodyweightFields
	// bodyweightDescCreatedAt is the schema descriptor for created_at field.
	bodyweightDescCreatedAt := bodyweightMixinFields1[0].Descriptor()
	// bodyweight.DefaultCreatedAt holds the default value on creation for the created_at field.
	bodyweight.DefaultCreatedAt = bodyweightDescCreatedAt.Default.(func() time.Time)
	// bodyweightDescUpdatedAt is the schema descriptor for updated_at field.
	bodyweightDescUpdatedAt := bodyweightMixinFields1[1].Descriptor()
	// bodyweight.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bodyweight.DefaultUpdatedAt = bodyweightDescUpdatedAt.Default.(func() time.Time)
	// bodyweight.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bodyweight.UpdateDefaultUpdatedAt = bodyweightDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bodyweightDescWeight is the schema descriptor for weight field.
	bodyweightDescWeight := bodyweightFields[0].Descriptor()
	// bodyweight.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	bodyweight.WeightValidator = bodyweightDescWeight.Validators[0].(func(float64) error)
	// bodyweightDescUnit is the schema descriptor for unit field.
	bodyweightDescUnit := bodyweightFields[1].Descriptor()
	// bodyweight.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	bodyweight.UnitValidator = bodyweightDescUnit.Validators[0].(func(string) error)
	// bodyweightDescID is the schema descriptor for id field.
	bodyweightDescID := bodyweightMixinFields0[0].Descriptor()
	// bodyweight.DefaultID holds the default value on creation for the id field.
	bodyweight.DefaultID = bodyweightDescID.Default.(func() uuid.UUID)
	exerciseMixin := schema.Exercise{}.Mixin()
	exerciseMixinFields0 := exerciseMixin[0].Fields()
	_ = exerciseMixinFields0
	exerciseMixinFields1 := exerciseMixin[1].Fields()
	_ = exerciseMixinFields1
	exerciseFields := schema.Exercise{}.Fields()
	_ = exerciseFields
	// exerciseDescCreatedAt is the schema descriptor for created_at field.
	exerciseDescCreatedAt := exerciseMixinFields1[0].Descriptor()
	// exercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	exercise.DefaultCreatedAt = exerciseDescCreatedAt.Default.(func() time.Time)
	// exerciseDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseDescUpdatedAt := exerciseMixinFields1[1].Descriptor()
	// exercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exercise.DefaultUpdatedAt = exerciseDescUpdatedAt.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exercise.UpdateDefaultUpdatedAt = exerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseDescID is the schema descriptor for id field.
	exerciseDescID := exerciseMixinFields0[0].Descriptor()
	// exercise.DefaultID holds the default value on creation for the id field.
	exercise.DefaultID = exerciseDescID.Default.(func() uuid.UUID)
	exerciseinstanceMixin := schema.ExerciseInstance{}.Mixin()
	exerciseinstanceMixinFields0 := exerciseinstanceMixin[0].Fields()
	_ = exerciseinstanceMixinFields0
	exerciseinstanceMixinFields1 := exerciseinstanceMixin[1].Fields()
	_ = exerciseinstanceMixinFields1
	exerciseinstanceFields := schema.ExerciseInstance{}.Fields()
	_ = exerciseinstanceFields
	// exerciseinstanceDescCreatedAt is the schema descriptor for created_at field.
	exerciseinstanceDescCreatedAt := exerciseinstanceMixinFields1[0].Descriptor()
	// exerciseinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	exerciseinstance.DefaultCreatedAt = exerciseinstanceDescCreatedAt.Default.(func() time.Time)
	// exerciseinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseinstanceDescUpdatedAt := exerciseinstanceMixinFields1[1].Descriptor()
	// exerciseinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exerciseinstance.DefaultUpdatedAt = exerciseinstanceDescUpdatedAt.Default.(func() time.Time)
	// exerciseinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exerciseinstance.UpdateDefaultUpdatedAt = exerciseinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseinstanceDescID is the schema descriptor for id field.
	exerciseinstanceDescID := exerciseinstanceMixinFields0[0].Descriptor()
	// exerciseinstance.DefaultID holds the default value on creation for the id field.
	exerciseinstance.DefaultID = exerciseinstanceDescID.Default.(func() uuid.UUID)
	exercisesetMixin := schema.ExerciseSet{}.Mixin()
	exercisesetMixinFields0 := exercisesetMixin[0].Fields()
	_ = exercisesetMixinFields0
	exercisesetMixinFields1 := exercisesetMixin[1].Fields()
	_ = exercisesetMixinFields1
	exercisesetFields := schema.ExerciseSet{}.Fields()
	_ = exercisesetFields
	// exercisesetDescCreatedAt is the schema descriptor for created_at field.
	exercisesetDescCreatedAt := exercisesetMixinFields1[0].Descriptor()
	// exerciseset.DefaultCreatedAt holds the default value on creation for the created_at field.
	exerciseset.DefaultCreatedAt = exercisesetDescCreatedAt.Default.(func() time.Time)
	// exercisesetDescUpdatedAt is the schema descriptor for updated_at field.
	exercisesetDescUpdatedAt := exercisesetMixinFields1[1].Descriptor()
	// exerciseset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exerciseset.DefaultUpdatedAt = exercisesetDescUpdatedAt.Default.(func() time.Time)
	// exerciseset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exerciseset.UpdateDefaultUpdatedAt = exercisesetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exercisesetDescStatus is the schema descriptor for status field.
	exercisesetDescStatus := exercisesetFields[4].Descriptor()
	// exerciseset.DefaultStatus holds the default value on creation for the status field.
	exerciseset.DefaultStatus = exercisesetDescStatus.Default.(int)
	// exercisesetDescID is the schema descriptor for id field.
	exercisesetDescID := exercisesetMixinFields0[0].Descriptor()
	// exerciseset.DefaultID holds the default value on creation for the id field.
	exerciseset.DefaultID = exercisesetDescID.Default.(func() uuid.UUID)
	privatetokenFields := schema.PrivateToken{}.Fields()
	_ = privatetokenFields
	// privatetokenDescToken is the schema descriptor for token field.
	privatetokenDescToken := privatetokenFields[1].Descriptor()
	// privatetoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	privatetoken.TokenValidator = privatetokenDescToken.Validators[0].(func(string) error)
	// privatetokenDescType is the schema descriptor for type field.
	privatetokenDescType := privatetokenFields[2].Descriptor()
	// privatetoken.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	privatetoken.TypeValidator = privatetokenDescType.Validators[0].(func(string) error)
	// privatetokenDescCreatedAt is the schema descriptor for created_at field.
	privatetokenDescCreatedAt := privatetokenFields[4].Descriptor()
	// privatetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	privatetoken.DefaultCreatedAt = privatetokenDescCreatedAt.Default.(func() time.Time)
	// privatetokenDescID is the schema descriptor for id field.
	privatetokenDescID := privatetokenFields[0].Descriptor()
	// privatetoken.DefaultID holds the default value on creation for the id field.
	privatetoken.DefaultID = privatetokenDescID.Default.(func() uuid.UUID)
	profileMixin := schema.Profile{}.Mixin()
	profileMixinFields0 := profileMixin[0].Fields()
	_ = profileMixinFields0
	profileMixinFields1 := profileMixin[1].Fields()
	_ = profileMixinFields1
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileMixinFields1[0].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileMixinFields1[1].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileMixinFields0[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[1].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[3].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	workoutMixin := schema.Workout{}.Mixin()
	workoutMixinFields0 := workoutMixin[0].Fields()
	_ = workoutMixinFields0
	workoutMixinFields1 := workoutMixin[1].Fields()
	_ = workoutMixinFields1
	workoutFields := schema.Workout{}.Fields()
	_ = workoutFields
	// workoutDescCreatedAt is the schema descriptor for created_at field.
	workoutDescCreatedAt := workoutMixinFields1[0].Descriptor()
	// workout.DefaultCreatedAt holds the default value on creation for the created_at field.
	workout.DefaultCreatedAt = workoutDescCreatedAt.Default.(func() time.Time)
	// workoutDescUpdatedAt is the schema descriptor for updated_at field.
	workoutDescUpdatedAt := workoutMixinFields1[1].Descriptor()
	// workout.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workout.DefaultUpdatedAt = workoutDescUpdatedAt.Default.(func() time.Time)
	// workout.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workout.UpdateDefaultUpdatedAt = workoutDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workoutDescID is the schema descriptor for id field.
	workoutDescID := workoutMixinFields0[0].Descriptor()
	// workout.DefaultID holds the default value on creation for the id field.
	workout.DefaultID = workoutDescID.Default.(func() uuid.UUID)
	workoutexerciseMixin := schema.WorkoutExercise{}.Mixin()
	workoutexerciseMixinFields0 := workoutexerciseMixin[0].Fields()
	_ = workoutexerciseMixinFields0
	workoutexerciseMixinFields1 := workoutexerciseMixin[1].Fields()
	_ = workoutexerciseMixinFields1
	workoutexerciseFields := schema.WorkoutExercise{}.Fields()
	_ = workoutexerciseFields
	// workoutexerciseDescCreatedAt is the schema descriptor for created_at field.
	workoutexerciseDescCreatedAt := workoutexerciseMixinFields1[0].Descriptor()
	// workoutexercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	workoutexercise.DefaultCreatedAt = workoutexerciseDescCreatedAt.Default.(func() time.Time)
	// workoutexerciseDescUpdatedAt is the schema descriptor for updated_at field.
	workoutexerciseDescUpdatedAt := workoutexerciseMixinFields1[1].Descriptor()
	// workoutexercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workoutexercise.DefaultUpdatedAt = workoutexerciseDescUpdatedAt.Default.(func() time.Time)
	// workoutexercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workoutexercise.UpdateDefaultUpdatedAt = workoutexerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workoutexerciseDescID is the schema descriptor for id field.
	workoutexerciseDescID := workoutexerciseMixinFields0[0].Descriptor()
	// workoutexercise.DefaultID holds the default value on creation for the id field.
	workoutexercise.DefaultID = workoutexerciseDescID.Default.(func() uuid.UUID)
	workoutlogMixin := schema.WorkoutLog{}.Mixin()
	workoutlogMixinFields0 := workoutlogMixin[0].Fields()
	_ = workoutlogMixinFields0
	workoutlogMixinFields1 := workoutlogMixin[1].Fields()
	_ = workoutlogMixinFields1
	workoutlogFields := schema.WorkoutLog{}.Fields()
	_ = workoutlogFields
	// workoutlogDescCreatedAt is the schema descriptor for created_at field.
	workoutlogDescCreatedAt := workoutlogMixinFields1[0].Descriptor()
	// workoutlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	workoutlog.DefaultCreatedAt = workoutlogDescCreatedAt.Default.(func() time.Time)
	// workoutlogDescUpdatedAt is the schema descriptor for updated_at field.
	workoutlogDescUpdatedAt := workoutlogMixinFields1[1].Descriptor()
	// workoutlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workoutlog.DefaultUpdatedAt = workoutlogDescUpdatedAt.Default.(func() time.Time)
	// workoutlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workoutlog.UpdateDefaultUpdatedAt = workoutlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workoutlogDescStatus is the schema descriptor for status field.
	workoutlogDescStatus := workoutlogFields[2].Descriptor()
	// workoutlog.DefaultStatus holds the default value on creation for the status field.
	workoutlog.DefaultStatus = workoutlogDescStatus.Default.(int)
	// workoutlogDescTotalActiveDurationSeconds is the schema descriptor for total_active_duration_seconds field.
	workoutlogDescTotalActiveDurationSeconds := workoutlogFields[3].Descriptor()
	// workoutlog.DefaultTotalActiveDurationSeconds holds the default value on creation for the total_active_duration_seconds field.
	workoutlog.DefaultTotalActiveDurationSeconds = workoutlogDescTotalActiveDurationSeconds.Default.(uint)
	// workoutlogDescTotalPauseDurationSeconds is the schema descriptor for total_pause_duration_seconds field.
	workoutlogDescTotalPauseDurationSeconds := workoutlogFields[4].Descriptor()
	// workoutlog.DefaultTotalPauseDurationSeconds holds the default value on creation for the total_pause_duration_seconds field.
	workoutlog.DefaultTotalPauseDurationSeconds = workoutlogDescTotalPauseDurationSeconds.Default.(uint)
	// workoutlogDescID is the schema descriptor for id field.
	workoutlogDescID := workoutlogMixinFields0[0].Descriptor()
	// workoutlog.DefaultID holds the default value on creation for the id field.
	workoutlog.DefaultID = workoutlogDescID.Default.(func() uuid.UUID)
}
