// Code generated by ent, DO NOT EDIT.

package ent

import (
	"rtglabs-go/ent/bodyweight"
	"rtglabs-go/ent/exercise"
	"rtglabs-go/ent/schema"
	"rtglabs-go/ent/session"
	"rtglabs-go/ent/user"
	"rtglabs-go/ent/workout"
	"rtglabs-go/ent/workoutexercise"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bodyweightFields := schema.Bodyweight{}.Fields()
	_ = bodyweightFields
	// bodyweightDescWeight is the schema descriptor for weight field.
	bodyweightDescWeight := bodyweightFields[2].Descriptor()
	// bodyweight.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	bodyweight.WeightValidator = bodyweightDescWeight.Validators[0].(func(float64) error)
	// bodyweightDescUnit is the schema descriptor for unit field.
	bodyweightDescUnit := bodyweightFields[3].Descriptor()
	// bodyweight.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	bodyweight.UnitValidator = bodyweightDescUnit.Validators[0].(func(string) error)
	// bodyweightDescCreatedAt is the schema descriptor for created_at field.
	bodyweightDescCreatedAt := bodyweightFields[4].Descriptor()
	// bodyweight.DefaultCreatedAt holds the default value on creation for the created_at field.
	bodyweight.DefaultCreatedAt = bodyweightDescCreatedAt.Default.(func() time.Time)
	// bodyweightDescUpdatedAt is the schema descriptor for updated_at field.
	bodyweightDescUpdatedAt := bodyweightFields[5].Descriptor()
	// bodyweight.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bodyweight.DefaultUpdatedAt = bodyweightDescUpdatedAt.Default.(func() time.Time)
	// bodyweight.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bodyweight.UpdateDefaultUpdatedAt = bodyweightDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bodyweightDescID is the schema descriptor for id field.
	bodyweightDescID := bodyweightFields[0].Descriptor()
	// bodyweight.DefaultID holds the default value on creation for the id field.
	bodyweight.DefaultID = bodyweightDescID.Default.(func() uuid.UUID)
	exerciseFields := schema.Exercise{}.Fields()
	_ = exerciseFields
	// exerciseDescName is the schema descriptor for name field.
	exerciseDescName := exerciseFields[1].Descriptor()
	// exercise.NameValidator is a validator for the "name" field. It is called by the builders before save.
	exercise.NameValidator = exerciseDescName.Validators[0].(func(string) error)
	// exerciseDescCreatedAt is the schema descriptor for created_at field.
	exerciseDescCreatedAt := exerciseFields[2].Descriptor()
	// exercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	exercise.DefaultCreatedAt = exerciseDescCreatedAt.Default.(func() time.Time)
	// exerciseDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseDescUpdatedAt := exerciseFields[3].Descriptor()
	// exercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exercise.DefaultUpdatedAt = exerciseDescUpdatedAt.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exercise.UpdateDefaultUpdatedAt = exerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseDescID is the schema descriptor for id field.
	exerciseDescID := exerciseFields[0].Descriptor()
	// exercise.DefaultID holds the default value on creation for the id field.
	exercise.DefaultID = exerciseDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[3].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	workoutFields := schema.Workout{}.Fields()
	_ = workoutFields
	// workoutDescName is the schema descriptor for name field.
	workoutDescName := workoutFields[2].Descriptor()
	// workout.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workout.NameValidator = workoutDescName.Validators[0].(func(string) error)
	// workoutDescCreatedAt is the schema descriptor for created_at field.
	workoutDescCreatedAt := workoutFields[3].Descriptor()
	// workout.DefaultCreatedAt holds the default value on creation for the created_at field.
	workout.DefaultCreatedAt = workoutDescCreatedAt.Default.(func() time.Time)
	// workoutDescUpdatedAt is the schema descriptor for updated_at field.
	workoutDescUpdatedAt := workoutFields[4].Descriptor()
	// workout.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workout.DefaultUpdatedAt = workoutDescUpdatedAt.Default.(func() time.Time)
	// workout.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workout.UpdateDefaultUpdatedAt = workoutDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workoutDescID is the schema descriptor for id field.
	workoutDescID := workoutFields[0].Descriptor()
	// workout.DefaultID holds the default value on creation for the id field.
	workout.DefaultID = workoutDescID.Default.(func() uuid.UUID)
	workoutexerciseFields := schema.WorkoutExercise{}.Fields()
	_ = workoutexerciseFields
	// workoutexerciseDescCreatedAt is the schema descriptor for created_at field.
	workoutexerciseDescCreatedAt := workoutexerciseFields[8].Descriptor()
	// workoutexercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	workoutexercise.DefaultCreatedAt = workoutexerciseDescCreatedAt.Default.(func() time.Time)
	// workoutexerciseDescUpdatedAt is the schema descriptor for updated_at field.
	workoutexerciseDescUpdatedAt := workoutexerciseFields[9].Descriptor()
	// workoutexercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workoutexercise.DefaultUpdatedAt = workoutexerciseDescUpdatedAt.Default.(func() time.Time)
	// workoutexercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workoutexercise.UpdateDefaultUpdatedAt = workoutexerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workoutexerciseDescID is the schema descriptor for id field.
	workoutexerciseDescID := workoutexerciseFields[0].Descriptor()
	// workoutexercise.DefaultID holds the default value on creation for the id field.
	workoutexercise.DefaultID = workoutexerciseDescID.Default.(func() uuid.UUID)
}
