// Code generated by ent, DO NOT EDIT.

package ent

import (
	"rtglabs-go/ent/bodyweight"
	"rtglabs-go/ent/exercise"
	"rtglabs-go/ent/profile"
	"rtglabs-go/ent/schema"
	"rtglabs-go/ent/session"
	"rtglabs-go/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bodyweightFields := schema.Bodyweight{}.Fields()
	_ = bodyweightFields
	// bodyweightDescWeight is the schema descriptor for weight field.
	bodyweightDescWeight := bodyweightFields[2].Descriptor()
	// bodyweight.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	bodyweight.WeightValidator = bodyweightDescWeight.Validators[0].(func(float64) error)
	// bodyweightDescUnit is the schema descriptor for unit field.
	bodyweightDescUnit := bodyweightFields[3].Descriptor()
	// bodyweight.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	bodyweight.UnitValidator = bodyweightDescUnit.Validators[0].(func(string) error)
	// bodyweightDescCreatedAt is the schema descriptor for created_at field.
	bodyweightDescCreatedAt := bodyweightFields[4].Descriptor()
	// bodyweight.DefaultCreatedAt holds the default value on creation for the created_at field.
	bodyweight.DefaultCreatedAt = bodyweightDescCreatedAt.Default.(func() time.Time)
	// bodyweightDescUpdatedAt is the schema descriptor for updated_at field.
	bodyweightDescUpdatedAt := bodyweightFields[5].Descriptor()
	// bodyweight.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bodyweight.DefaultUpdatedAt = bodyweightDescUpdatedAt.Default.(func() time.Time)
	// bodyweight.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bodyweight.UpdateDefaultUpdatedAt = bodyweightDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bodyweightDescID is the schema descriptor for id field.
	bodyweightDescID := bodyweightFields[0].Descriptor()
	// bodyweight.DefaultID holds the default value on creation for the id field.
	bodyweight.DefaultID = bodyweightDescID.Default.(func() uuid.UUID)
	exerciseMixin := schema.Exercise{}.Mixin()
	exerciseMixinFields0 := exerciseMixin[0].Fields()
	_ = exerciseMixinFields0
	exerciseMixinFields1 := exerciseMixin[1].Fields()
	_ = exerciseMixinFields1
	exerciseMixinFields2 := exerciseMixin[2].Fields()
	_ = exerciseMixinFields2
	exerciseFields := schema.Exercise{}.Fields()
	_ = exerciseFields
	// exerciseDescCreateTime is the schema descriptor for create_time field.
	exerciseDescCreateTime := exerciseMixinFields0[0].Descriptor()
	// exercise.DefaultCreateTime holds the default value on creation for the create_time field.
	exercise.DefaultCreateTime = exerciseDescCreateTime.Default.(func() time.Time)
	// exerciseDescUpdateTime is the schema descriptor for update_time field.
	exerciseDescUpdateTime := exerciseMixinFields0[1].Descriptor()
	// exercise.DefaultUpdateTime holds the default value on creation for the update_time field.
	exercise.DefaultUpdateTime = exerciseDescUpdateTime.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	exercise.UpdateDefaultUpdateTime = exerciseDescUpdateTime.UpdateDefault.(func() time.Time)
	// exerciseDescCreatedAt is the schema descriptor for created_at field.
	exerciseDescCreatedAt := exerciseMixinFields2[0].Descriptor()
	// exercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	exercise.DefaultCreatedAt = exerciseDescCreatedAt.Default.(func() time.Time)
	// exerciseDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseDescUpdatedAt := exerciseMixinFields2[1].Descriptor()
	// exercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exercise.DefaultUpdatedAt = exerciseDescUpdatedAt.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exercise.UpdateDefaultUpdatedAt = exerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseDescID is the schema descriptor for id field.
	exerciseDescID := exerciseMixinFields1[0].Descriptor()
	// exercise.DefaultID holds the default value on creation for the id field.
	exercise.DefaultID = exerciseDescID.Default.(func() uuid.UUID)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileFields[7].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[8].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[3].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
