// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rtglabs-go/ent/exercise"
	"rtglabs-go/ent/exerciseinstance"
	"rtglabs-go/ent/predicate"
	"rtglabs-go/ent/workout"
	"rtglabs-go/ent/workoutexercise"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkoutExerciseQuery is the builder for querying WorkoutExercise entities.
type WorkoutExerciseQuery struct {
	config
	ctx                  *QueryContext
	order                []workoutexercise.OrderOption
	inters               []Interceptor
	predicates           []predicate.WorkoutExercise
	withWorkout          *WorkoutQuery
	withExercise         *ExerciseQuery
	withExerciseInstance *ExerciseInstanceQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkoutExerciseQuery builder.
func (weq *WorkoutExerciseQuery) Where(ps ...predicate.WorkoutExercise) *WorkoutExerciseQuery {
	weq.predicates = append(weq.predicates, ps...)
	return weq
}

// Limit the number of records to be returned by this query.
func (weq *WorkoutExerciseQuery) Limit(limit int) *WorkoutExerciseQuery {
	weq.ctx.Limit = &limit
	return weq
}

// Offset to start from.
func (weq *WorkoutExerciseQuery) Offset(offset int) *WorkoutExerciseQuery {
	weq.ctx.Offset = &offset
	return weq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (weq *WorkoutExerciseQuery) Unique(unique bool) *WorkoutExerciseQuery {
	weq.ctx.Unique = &unique
	return weq
}

// Order specifies how the records should be ordered.
func (weq *WorkoutExerciseQuery) Order(o ...workoutexercise.OrderOption) *WorkoutExerciseQuery {
	weq.order = append(weq.order, o...)
	return weq
}

// QueryWorkout chains the current query on the "workout" edge.
func (weq *WorkoutExerciseQuery) QueryWorkout() *WorkoutQuery {
	query := (&WorkoutClient{config: weq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := weq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := weq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workoutexercise.Table, workoutexercise.FieldID, selector),
			sqlgraph.To(workout.Table, workout.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workoutexercise.WorkoutTable, workoutexercise.WorkoutColumn),
		)
		fromU = sqlgraph.SetNeighbors(weq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExercise chains the current query on the "exercise" edge.
func (weq *WorkoutExerciseQuery) QueryExercise() *ExerciseQuery {
	query := (&ExerciseClient{config: weq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := weq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := weq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workoutexercise.Table, workoutexercise.FieldID, selector),
			sqlgraph.To(exercise.Table, exercise.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workoutexercise.ExerciseTable, workoutexercise.ExerciseColumn),
		)
		fromU = sqlgraph.SetNeighbors(weq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExerciseInstance chains the current query on the "exercise_instance" edge.
func (weq *WorkoutExerciseQuery) QueryExerciseInstance() *ExerciseInstanceQuery {
	query := (&ExerciseInstanceClient{config: weq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := weq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := weq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workoutexercise.Table, workoutexercise.FieldID, selector),
			sqlgraph.To(exerciseinstance.Table, exerciseinstance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workoutexercise.ExerciseInstanceTable, workoutexercise.ExerciseInstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(weq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkoutExercise entity from the query.
// Returns a *NotFoundError when no WorkoutExercise was found.
func (weq *WorkoutExerciseQuery) First(ctx context.Context) (*WorkoutExercise, error) {
	nodes, err := weq.Limit(1).All(setContextOp(ctx, weq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workoutexercise.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) FirstX(ctx context.Context) *WorkoutExercise {
	node, err := weq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkoutExercise ID from the query.
// Returns a *NotFoundError when no WorkoutExercise ID was found.
func (weq *WorkoutExerciseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = weq.Limit(1).IDs(setContextOp(ctx, weq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workoutexercise.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := weq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkoutExercise entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkoutExercise entity is found.
// Returns a *NotFoundError when no WorkoutExercise entities are found.
func (weq *WorkoutExerciseQuery) Only(ctx context.Context) (*WorkoutExercise, error) {
	nodes, err := weq.Limit(2).All(setContextOp(ctx, weq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workoutexercise.Label}
	default:
		return nil, &NotSingularError{workoutexercise.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) OnlyX(ctx context.Context) *WorkoutExercise {
	node, err := weq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkoutExercise ID in the query.
// Returns a *NotSingularError when more than one WorkoutExercise ID is found.
// Returns a *NotFoundError when no entities are found.
func (weq *WorkoutExerciseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = weq.Limit(2).IDs(setContextOp(ctx, weq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workoutexercise.Label}
	default:
		err = &NotSingularError{workoutexercise.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := weq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkoutExercises.
func (weq *WorkoutExerciseQuery) All(ctx context.Context) ([]*WorkoutExercise, error) {
	ctx = setContextOp(ctx, weq.ctx, ent.OpQueryAll)
	if err := weq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkoutExercise, *WorkoutExerciseQuery]()
	return withInterceptors[[]*WorkoutExercise](ctx, weq, qr, weq.inters)
}

// AllX is like All, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) AllX(ctx context.Context) []*WorkoutExercise {
	nodes, err := weq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkoutExercise IDs.
func (weq *WorkoutExerciseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if weq.ctx.Unique == nil && weq.path != nil {
		weq.Unique(true)
	}
	ctx = setContextOp(ctx, weq.ctx, ent.OpQueryIDs)
	if err = weq.Select(workoutexercise.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := weq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (weq *WorkoutExerciseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, weq.ctx, ent.OpQueryCount)
	if err := weq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, weq, querierCount[*WorkoutExerciseQuery](), weq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) CountX(ctx context.Context) int {
	count, err := weq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (weq *WorkoutExerciseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, weq.ctx, ent.OpQueryExist)
	switch _, err := weq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (weq *WorkoutExerciseQuery) ExistX(ctx context.Context) bool {
	exist, err := weq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkoutExerciseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (weq *WorkoutExerciseQuery) Clone() *WorkoutExerciseQuery {
	if weq == nil {
		return nil
	}
	return &WorkoutExerciseQuery{
		config:               weq.config,
		ctx:                  weq.ctx.Clone(),
		order:                append([]workoutexercise.OrderOption{}, weq.order...),
		inters:               append([]Interceptor{}, weq.inters...),
		predicates:           append([]predicate.WorkoutExercise{}, weq.predicates...),
		withWorkout:          weq.withWorkout.Clone(),
		withExercise:         weq.withExercise.Clone(),
		withExerciseInstance: weq.withExerciseInstance.Clone(),
		// clone intermediate query.
		sql:  weq.sql.Clone(),
		path: weq.path,
	}
}

// WithWorkout tells the query-builder to eager-load the nodes that are connected to
// the "workout" edge. The optional arguments are used to configure the query builder of the edge.
func (weq *WorkoutExerciseQuery) WithWorkout(opts ...func(*WorkoutQuery)) *WorkoutExerciseQuery {
	query := (&WorkoutClient{config: weq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	weq.withWorkout = query
	return weq
}

// WithExercise tells the query-builder to eager-load the nodes that are connected to
// the "exercise" edge. The optional arguments are used to configure the query builder of the edge.
func (weq *WorkoutExerciseQuery) WithExercise(opts ...func(*ExerciseQuery)) *WorkoutExerciseQuery {
	query := (&ExerciseClient{config: weq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	weq.withExercise = query
	return weq
}

// WithExerciseInstance tells the query-builder to eager-load the nodes that are connected to
// the "exercise_instance" edge. The optional arguments are used to configure the query builder of the edge.
func (weq *WorkoutExerciseQuery) WithExerciseInstance(opts ...func(*ExerciseInstanceQuery)) *WorkoutExerciseQuery {
	query := (&ExerciseInstanceClient{config: weq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	weq.withExerciseInstance = query
	return weq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkoutExercise.Query().
//		GroupBy(workoutexercise.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (weq *WorkoutExerciseQuery) GroupBy(field string, fields ...string) *WorkoutExerciseGroupBy {
	weq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkoutExerciseGroupBy{build: weq}
	grbuild.flds = &weq.ctx.Fields
	grbuild.label = workoutexercise.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WorkoutExercise.Query().
//		Select(workoutexercise.FieldCreatedAt).
//		Scan(ctx, &v)
func (weq *WorkoutExerciseQuery) Select(fields ...string) *WorkoutExerciseSelect {
	weq.ctx.Fields = append(weq.ctx.Fields, fields...)
	sbuild := &WorkoutExerciseSelect{WorkoutExerciseQuery: weq}
	sbuild.label = workoutexercise.Label
	sbuild.flds, sbuild.scan = &weq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkoutExerciseSelect configured with the given aggregations.
func (weq *WorkoutExerciseQuery) Aggregate(fns ...AggregateFunc) *WorkoutExerciseSelect {
	return weq.Select().Aggregate(fns...)
}

func (weq *WorkoutExerciseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range weq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, weq); err != nil {
				return err
			}
		}
	}
	for _, f := range weq.ctx.Fields {
		if !workoutexercise.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if weq.path != nil {
		prev, err := weq.path(ctx)
		if err != nil {
			return err
		}
		weq.sql = prev
	}
	return nil
}

func (weq *WorkoutExerciseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkoutExercise, error) {
	var (
		nodes       = []*WorkoutExercise{}
		withFKs     = weq.withFKs
		_spec       = weq.querySpec()
		loadedTypes = [3]bool{
			weq.withWorkout != nil,
			weq.withExercise != nil,
			weq.withExerciseInstance != nil,
		}
	)
	if weq.withWorkout != nil || weq.withExercise != nil || weq.withExerciseInstance != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, workoutexercise.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkoutExercise).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkoutExercise{config: weq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, weq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := weq.withWorkout; query != nil {
		if err := weq.loadWorkout(ctx, query, nodes, nil,
			func(n *WorkoutExercise, e *Workout) { n.Edges.Workout = e }); err != nil {
			return nil, err
		}
	}
	if query := weq.withExercise; query != nil {
		if err := weq.loadExercise(ctx, query, nodes, nil,
			func(n *WorkoutExercise, e *Exercise) { n.Edges.Exercise = e }); err != nil {
			return nil, err
		}
	}
	if query := weq.withExerciseInstance; query != nil {
		if err := weq.loadExerciseInstance(ctx, query, nodes, nil,
			func(n *WorkoutExercise, e *ExerciseInstance) { n.Edges.ExerciseInstance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (weq *WorkoutExerciseQuery) loadWorkout(ctx context.Context, query *WorkoutQuery, nodes []*WorkoutExercise, init func(*WorkoutExercise), assign func(*WorkoutExercise, *Workout)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*WorkoutExercise)
	for i := range nodes {
		if nodes[i].workout_workout_exercises == nil {
			continue
		}
		fk := *nodes[i].workout_workout_exercises
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workout.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workout_workout_exercises" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (weq *WorkoutExerciseQuery) loadExercise(ctx context.Context, query *ExerciseQuery, nodes []*WorkoutExercise, init func(*WorkoutExercise), assign func(*WorkoutExercise, *Exercise)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*WorkoutExercise)
	for i := range nodes {
		if nodes[i].exercise_workout_exercises == nil {
			continue
		}
		fk := *nodes[i].exercise_workout_exercises
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(exercise.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "exercise_workout_exercises" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (weq *WorkoutExerciseQuery) loadExerciseInstance(ctx context.Context, query *ExerciseInstanceQuery, nodes []*WorkoutExercise, init func(*WorkoutExercise), assign func(*WorkoutExercise, *ExerciseInstance)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*WorkoutExercise)
	for i := range nodes {
		if nodes[i].exercise_instance_workout_exercises == nil {
			continue
		}
		fk := *nodes[i].exercise_instance_workout_exercises
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(exerciseinstance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "exercise_instance_workout_exercises" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (weq *WorkoutExerciseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := weq.querySpec()
	_spec.Node.Columns = weq.ctx.Fields
	if len(weq.ctx.Fields) > 0 {
		_spec.Unique = weq.ctx.Unique != nil && *weq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, weq.driver, _spec)
}

func (weq *WorkoutExerciseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workoutexercise.Table, workoutexercise.Columns, sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeUUID))
	_spec.From = weq.sql
	if unique := weq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if weq.path != nil {
		_spec.Unique = true
	}
	if fields := weq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workoutexercise.FieldID)
		for i := range fields {
			if fields[i] != workoutexercise.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := weq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := weq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := weq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := weq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (weq *WorkoutExerciseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(weq.driver.Dialect())
	t1 := builder.Table(workoutexercise.Table)
	columns := weq.ctx.Fields
	if len(columns) == 0 {
		columns = workoutexercise.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if weq.sql != nil {
		selector = weq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if weq.ctx.Unique != nil && *weq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range weq.predicates {
		p(selector)
	}
	for _, p := range weq.order {
		p(selector)
	}
	if offset := weq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := weq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkoutExerciseGroupBy is the group-by builder for WorkoutExercise entities.
type WorkoutExerciseGroupBy struct {
	selector
	build *WorkoutExerciseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wegb *WorkoutExerciseGroupBy) Aggregate(fns ...AggregateFunc) *WorkoutExerciseGroupBy {
	wegb.fns = append(wegb.fns, fns...)
	return wegb
}

// Scan applies the selector query and scans the result into the given value.
func (wegb *WorkoutExerciseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wegb.build.ctx, ent.OpQueryGroupBy)
	if err := wegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkoutExerciseQuery, *WorkoutExerciseGroupBy](ctx, wegb.build, wegb, wegb.build.inters, v)
}

func (wegb *WorkoutExerciseGroupBy) sqlScan(ctx context.Context, root *WorkoutExerciseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wegb.fns))
	for _, fn := range wegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wegb.flds)+len(wegb.fns))
		for _, f := range *wegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkoutExerciseSelect is the builder for selecting fields of WorkoutExercise entities.
type WorkoutExerciseSelect struct {
	*WorkoutExerciseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wes *WorkoutExerciseSelect) Aggregate(fns ...AggregateFunc) *WorkoutExerciseSelect {
	wes.fns = append(wes.fns, fns...)
	return wes
}

// Scan applies the selector query and scans the result into the given value.
func (wes *WorkoutExerciseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wes.ctx, ent.OpQuerySelect)
	if err := wes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkoutExerciseQuery, *WorkoutExerciseSelect](ctx, wes.WorkoutExerciseQuery, wes, wes.inters, v)
}

func (wes *WorkoutExerciseSelect) sqlScan(ctx context.Context, root *WorkoutExerciseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wes.fns))
	for _, fn := range wes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
