// Code generated by ent, DO NOT EDIT.

package exerciseinstance

import (
	"rtglabs-go/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.FieldNotNull(FieldDeletedAt))
}

// HasExercise applies the HasEdge predicate on the "exercise" edge.
func HasExercise() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExerciseTable, ExerciseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExerciseWith applies the HasEdge predicate on the "exercise" edge with a given conditions (other predicates).
func HasExerciseWith(preds ...predicate.Exercise) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := newExerciseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkoutExercises applies the HasEdge predicate on the "workout_exercises" edge.
func HasWorkoutExercises() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkoutExercisesTable, WorkoutExercisesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkoutExercisesWith applies the HasEdge predicate on the "workout_exercises" edge with a given conditions (other predicates).
func HasWorkoutExercisesWith(preds ...predicate.WorkoutExercise) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := newWorkoutExercisesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExerciseSets applies the HasEdge predicate on the "exercise_sets" edge.
func HasExerciseSets() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExerciseSetsTable, ExerciseSetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExerciseSetsWith applies the HasEdge predicate on the "exercise_sets" edge with a given conditions (other predicates).
func HasExerciseSetsWith(preds ...predicate.ExerciseSet) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := newExerciseSetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkoutLog applies the HasEdge predicate on the "workout_log" edge.
func HasWorkoutLog() predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkoutLogTable, WorkoutLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkoutLogWith applies the HasEdge predicate on the "workout_log" edge with a given conditions (other predicates).
func HasWorkoutLogWith(preds ...predicate.WorkoutLog) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(func(s *sql.Selector) {
		step := newWorkoutLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExerciseInstance) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExerciseInstance) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExerciseInstance) predicate.ExerciseInstance {
	return predicate.ExerciseInstance(sql.NotPredicates(p))
}
