// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bodyweight is the predicate function for bodyweight builders.
type Bodyweight func(*sql.Selector)

// Exercise is the predicate function for exercise builders.
type Exercise func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workout is the predicate function for workout builders.
type Workout func(*sql.Selector)

// WorkoutExercise is the predicate function for workoutexercise builders.
type WorkoutExercise func(*sql.Selector)
